version: "2"
services:
  uwsgi:
    container_name: app
    build: ./app
    command: uwsgi --ini uwsgi.ini
    expose:
      - "3031"
  nginx:
    container_name: nginx
    build: ./nginx
    links:
      - uwsgi
    volumes_from:
      - uwsgi
    ports:
      - "80:80"
